import { useState } from 'react'
import './App.css'

// this element will contain cards generated by order generator and represent the first tree orders  to fulfill
const Orders = (props) => {
  return(
    <div class="orders">
    </div>
  )
}

// this is for buttons I'll need
const handleClick =()=>{
  console.log('click click')
}
const Button = (props) =>{
  return(
    <div>
      <button onClick={handleClick}>
        Click Me 
      </button>
    </div>
  )
}



// that's where the magic happens and from where it is exported(-:
function App() {
  return (
      <div class="container">
        <Orders/>
        <Button/>
        <Button/>
        <Button/>
      </div>
  )
}

export default App
